### ISSUE TITLE
Can't adjust volume on incall.

### ISSUE THREAD

**Issue by ch3paz** [Deepflex/android_device_elephone_p9000#81]
When receiving an incall the volume isn't adjustable via the rocker at the side of the phone. The Slider on the top is moving but the volume stay constant (and to loud BTW.).

I think this is since RC4. Done clean flash after flashing stockrom complete.

**Comment by andyrichardson** [comment]
I've had this issue since build 3. It persists when using headphones also.

**Comment by ch3paz** [comment]
Possibly this doesn't work since day one of the CM-Port. I noticed it first in RC4 i think. I'm using the Elephone sparely for phonecalls :)

**Comment by andyrichardson** [comment]
I managed to find this error in Build 4 (SIM fix version) which I believe is related.

```
09-22 18:36:49.948   314   835 W AudioMTKGainController: error, stream -1 is invalid, use 3 instead
09-22 18:36:49.949   314   835 W AudioMTKGainController: error, index -1 is invalid, use max 15 instead

```

**Comment by robot-army** [comment]
Confirmed here as well

**Comment by ch3paz** [comment]
Phone is abandoned, so this issue is also.
