### ISSUE TITLE
Error compiling p9000 lineageos 14.1

### ISSUE THREAD

**Issue by ishbutz** [Deepflex/android_device_elephone_p9000#86]
Hi
I compiled 13.0 rom without much problems (it's my 1st time compiling android & lineage/cm rom) but when I try to compile 14.1 rom (with leskal 14.1 branches) I always get the same compile error:

(I'm using Linux mint with lineageos 14.1 source)
```
system/netd/server/SoftapController.cpp:101:26: error: use of undeclared identifier 'hostapd_unix_file'
    ctrl = wpa_ctrl_open(hostapd_unix_file.c_str());
                         ^
system/netd/server/SoftapController.cpp:111:30: error: use of undeclared identifier 'hostapd_unix_file'
        ctrl = wpa_ctrl_open(hostapd_unix_file.c_str());
                             ^
system/netd/server/SoftapController.cpp:219:13: error: use of undeclared identifier 'hostapd_unix_file'
            hostapd_unix_file = wbuf;
            ^
3 errors generated.
build/core/binary.mk:986: recipe for target '/media/mik/dev1/android/system/out/target/product/p9000/obj/EXECUTABLES/netd_intermediates/SoftapController.o' failed
make: *** [/media/mik/dev1/android/system/out/target/product/p9000/obj/EXECUTABLES/netd_intermediates/SoftapController.o] Error 1
```

I used these commands to compile   :
```
sh device/elephone/p9000/patches/install.sh
export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx8g"
./prebuilts/sdk/tools/jack-admin kill-server
./prebuilts/sdk/tools/jack-admin start-server
. build/envsetup.sh
brunch p9000
```

I would like to help but now I'm stuck and I can't find much informations about this error...
Did someone get the same issue ?

**Comment by leskal** [comment]
Do not apply the patch and try again. The patch needs to be updated

**Comment by ishbutz** [comment]
Thanks for your reply.
I tried these commands but I still got the same error:

```
sh device/elephone/p9000/patches/uninstall.sh
repo sync
make clobber
. build/envsetup.sh
brunch p9000
```


The uninstall.sh worked, I think... But I'm not sure for the other commands.
Do I miss something to rebuild correctly ?

**Comment by leskal** [comment]
Soon i will update the patch. But for proper unistall of patch i recommend to delete the netd folder and do repo sync

**Comment by leskal** [comment]
https://github.com/leskal/android_device_elephone_p9000/commit/edd0aeee19cddbdf5bdd727dc2c90434ce3060b8
