### ISSUE TITLE
Can't boot my cm14.1 builds flashed with twrp

### ISSUE THREAD

**Issue by ishbutz** [Deepflex/android_device_elephone_p9000#88]
Hello,
I built successfully cm14.1 branch from Leskal. I tried to flash the zip from out dir through TWRP but I got 2 Errors while flashing (E:unknown command) and the system doesn't boot.
I also tried to build and flash TWRP7.1 with spft but it does not work.
Is it already possible to run cm14.1 builds on the p9000 ?

**Comment by leskal** [comment]
If cm-14.1 was booting, we won't working for cm-13

**Comment by ishbutz** [comment]
OK thank you.
Can you please tell me if this problem comes from kernel booting ? (the log refers to a problem with "kernel reset", if I remember well) or from specific device partitions (preloader, boot,...) ? or if it's something else....
